### PR TITLE
fix scrape failures on ch 18.5.x+

### PR DESCRIPTION
**Pull request by tkroman**

### CODE REVIEW

**Comment by valo** [comment]
I encountered this problem just now and saw your PR. Thanks for fixing it. Now I need to figure out how to get a docker container with the fix :-)

**Comment by tkroman** [comment]
@valo https://hub.docker.com/r/tkroman/clickhouse_exporter_fresh/

built a newer docker based on my fork. as a bonus you get an actually working dockerfile :)

**Comment by valo** [comment]
Deployed the image and it works great! Thanks for providing this

**Comment by f1yegor** [comment]
Thanks @tkroman . Do you mind if I borrow you build file for docker-image?

**Comment by tkroman** [comment]
Sure, go ahead.

**Pull request merged**
